import os
import sys
import platform
import glob as pyglob

OS_NAME = platform.system();
LIB_DIR=os.environ['LIB_DIR'];
BIN_DIR=os.environ['BIN_DIR'];

env=DefaultEnvironment().Clone()
RIVE_CPP_FILES = [File(p) for p in pyglob.glob("rive-cpp/src/**/*.cpp", recursive=True)]

SOURCES=Glob('base/*.c') + Glob('*.c') + Glob('*.cpp') + RIVE_CPP_FILES + Glob('rive/*.cpp');

APP_CXXFLAGS = ''
if platform.system() == 'Windows':
  APP_CXXFLAGS += ' /std:c++latest -DRIVE_BUILD -D_USE_MATH_DEFINES -DNOMINMAX '
else:
  APP_CXXFLAGS += ' -std=c++17 '

env['CXXFLAGS'] = env['CXXFLAGS'] + APP_CXXFLAGS

EXPORT_DEF=''
if OS_NAME == 'Windows' and os.environ['TOOLS_NAME'] == '':
  EXPORT_DEF = ' /DEF:"src/rive.def" '

if 'BUILD_SHARED' in os.environ and os.environ['BUILD_SHARED'] == 'True':
  LIBS=['awtk'];
  LINKFLAGS=env['LINKFLAGS'] + EXPORT_DEF 
  env.SharedLibrary(os.path.join(BIN_DIR, 'rive'), SOURCES, LIBS=LIBS, LINKFLAGS=LINKFLAGS);
else:
  env.Library(os.path.join(LIB_DIR, 'rive'), SOURCES);

